import { cardName } from './i18n';
import type { Language, PublicGame } from './types';
import type { ComposeMode, AutoMode } from './playAssist';

const copy = {
  vi: {
    SINGLE: '1 · Lá chức năng', PAIR: '2 · Cặp cùng tên', TRIPLE: '3 · Bộ ba cùng tên', PLUS_PLUS: '++ · Tăng sức mạnh',
    mode: 'Cách đánh', choose: 'Chọn bài bên dưới', matching: 'Chọn đủ {n} lá cùng tên. Đổi loại bài sẽ bắt đầu nhóm mới.', plus: 'Chọn ++ và một lá Tấn công, Xem tương lai hoặc Dơi.', target: 'Chọn người nhận tác động', requested: 'Gọi tên lá muốn lấy', confirm: 'Kiểm tra rồi bấm Đánh bài. Bạn vẫn có thể đánh tiếp trước khi rút.',
    missingTarget: 'Chưa chọn người. Bấm một tên bên dưới.', noTarget: 'Không có người phù hợp để dùng lá này.', protected: 'Cứu nổ tự dùng khi rút mèo nổ. Không dùng để kết thúc lượt. Không dùng Nope trong lượt thường. Bài mèo cần ghép cặp hoặc bộ ba.', invalid: 'Nhóm chưa hợp lệ. Chọn cách đánh và các lá tương ứng.',
    guide: 'Hướng dẫn nhanh', guideIntro: 'Mục tiêu: là người cuối cùng còn sống. Mỗi lượt đánh 0 hoặc nhiều lá rồi rút 1 lá để kết thúc. Rút mèo nổ mà không có Cứu nổ sẽ bị loại.',
    guideCombo: 'Cặp cùng tên: lấy ngẫu nhiên 1 lá từ người được chọn. Bộ ba cùng tên: gọi tên 1 loại bài, lấy 1 nếu họ có. Không có combo 4 trong luật phòng này.',
    guideNope: 'Nope chặn hành động đang chờ trong 7 giây; có thể Nope tiếp để đảo kết quả. Không chặn mèo nổ hoặc Cứu nổ. Bấm Bỏ qua khi không muốn chặn.',
    guideDebt: 'Tấn công chuyển số lượt còn nợ và cộng 2; nếu không bị tấn công thì chuyển 2 lượt. Bỏ lượt chỉ bỏ 1 lượt. Xin bài: người được chọn quyết định cho lá nào.',
    guideHints: 'Viền chấm: chọn được trong cách đánh hiện tại. Viền xanh và nhãn Gợi ý: đề xuất cơ bản, chỉ dùng bài bạn biết. Có thể bỏ qua gợi ý; không đảm bảo thắng.',
    guideAuto: 'Tự chơi là hỗ trợ của ứng dụng, tắt mặc định mỗi ván. Chế độ cơ bản ưu tiên xem tương lai, tránh mèo nổ đã biết và ghép bài mèo; giữ Cứu nổ, bỏ qua Nope, chèn mèo nổ xuống đáy và chọn Búa. Chỉ chạy khi tab mở và đã kết nối. Bấm lá bất kỳ để dừng.',
    hint: 'Gợi ý', playable: 'Chọn được', escape: 'Bạn đã xem thấy mèo nổ ở trên cùng. Có thể dùng lá này để tránh rút ngay.', future: 'Xem trước bộ rút để quyết định an toàn hơn.', pair: 'Bạn có một cặp bài mèo. Ghép cặp để lấy ngẫu nhiên một lá.', draw: 'Không có đề xuất đặc biệt. Bạn có thể rút để kết thúc lượt hoặc chọn lá chức năng.', applyHint: 'Chọn bài gợi ý', auto: 'Tự chơi', OFF: 'Tắt', DRAW: 'Tự rút khi còn 5 giây', BASIC: 'Tự chơi cơ bản', autoRunning: 'Đang tự chơi. Bấm bài để chuyển về điều khiển tay.', drawRunning: 'Sẽ rút khi còn 5 giây. Bạn vẫn có thể đánh bài trước đó.', autoQueued: 'Hành động tự động tiếp theo sau khoảng 1,5 giây.', expired: 'Hết giờ · đang chờ server xử lý',
    TURN: 'Lượt thường · 30 giây', NOPE_WINDOW: 'Cửa sổ Nope · 7 giây', FAVOR_CHOICE: 'Chọn bài để cho · 20 giây', DEFUSE_INSERT: 'Chèn mèo nổ · 20 giây', HIP_CAT_CHOICE: 'Kéo / búa / bao · 20 giây', HIP_BAT_DISCARD: 'Dơi: bỏ một lá · 20 giây', BATTLE_HAMSTER_DISCARD: 'Hamster: bỏ đến còn một lá · 20 giây', ARCHAEOLOGY_CHOICE: 'Chọn bài từ bộ bỏ · 20 giây', FINISHED: 'Ván đã kết thúc',
    timeoutTURN: 'Hết giờ: server rút 1 lá; nếu nổ vẫn xử lý Cứu nổ và số lượt nợ.', timeoutNOPE_WINDOW: 'Hết giờ: server áp dụng hoặc hủy hành động theo số Nope chẵn / lẻ.', timeoutFAVOR_CHOICE: 'Hết giờ: server chọn ngẫu nhiên 1 lá để cho.', timeoutDEFUSE_INSERT: 'Hết giờ: server chọn ngẫu nhiên một khe hợp lệ, vẫn che vị trí giữa.', timeoutHIP_CAT_CHOICE: 'Hết giờ: server chọn ngẫu nhiên cho người chưa trả lời.', timeoutHIP_BAT_DISCARD: 'Hết giờ: server bỏ ngẫu nhiên 1 lá.', timeoutBATTLE_HAMSTER_DISCARD: 'Hết giờ: server bỏ ngẫu nhiên các lá dư, giữ lại 1 lá.', timeoutARCHAEOLOGY_CHOICE: 'Hết giờ: server chọn ngẫu nhiên một lá hợp lệ.',
    yourChoice: 'Bạn cần trả lời bước này.', waitingFor: 'Đang chờ {name}.', passed: 'Bạn đã bỏ qua. Vẫn có thể Nope nếu đổi ý.', chooseOne: 'Bấm đúng một lá trong tay, rồi Xác nhận.', hamster: 'Cần bỏ thêm {n} lá. Mỗi lần chọn một lá.', selected: 'Đã chọn', cancel: 'Bỏ chọn',
  },
  en: {
    SINGLE: '1 · Action card', PAIR: '2 · Matching pair', TRIPLE: '3 · Matching triple', PLUS_PLUS: '++ · Boost',
    mode: 'Play mode', choose: 'Select cards below', matching: 'Select {n} cards of the same type. Changing type starts a new group.', plus: 'Select ++ and Attack, See the Future or Hip Bat.', target: 'Choose a target', requested: 'Name the card to take', confirm: 'Review, then press Play selected. You can keep playing before drawing.', missingTarget: 'Choose a player by pressing a name below.', noTarget: 'No eligible target for this card.', protected: 'Defuse is used automatically when you draw an explosion. Nope belongs in the response window. Cat cards need a pair or triple.', invalid: 'This group is incomplete. Select a mode and matching cards.',
    guide: 'Quick guide', guideIntro: 'Be the last player alive. Play zero or more cards, then draw one to end each turn. Drawing an explosion without Defuse eliminates you.', guideCombo: 'Matching pair: steal one random card from your chosen target. Matching triple: request a type and take one if they have it. This room has no four-card combo.', guideNope: 'Nope blocks a pending action during its 7-second window; further Nopes reverse it again. Explosions and Defuse cannot be Noped. Pass if you do not want to block.', guideDebt: 'Attack passes remaining owed turns plus two; an ordinary Attack passes two. Skip removes only one turn. Favor lets the target choose the gift.', guideHints: 'Dotted border: selectable in the current mode. Green border and Suggestion badge: basic advice using only information you can see. Advice does not guarantee a win.', guideAuto: 'Autoplay is an app helper, off by default for each match. Basic mode scouts the future, avoids known explosions and plays cat pairs; it saves Defuse, passes Nope, inserts explosions at the bottom and chooses Rock. Runs only in a visible, connected tab. Select any card to stop.',
    hint: 'Suggestion', playable: 'Selectable', escape: 'Your future view shows an explosion on top. This card can avoid drawing it now.', future: 'Look ahead before deciding what to draw.', pair: 'You have a matching cat pair. Use it to steal one random card.', draw: 'No special suggestion. Draw to end your turn or choose an action card.', applyHint: 'Select suggested cards', auto: 'Autoplay', OFF: 'Off', DRAW: 'Draw at 5 seconds', BASIC: 'Basic autoplay', autoRunning: 'Autoplay is running. Select a card to take manual control.', drawRunning: 'Will draw at 5 seconds. You can still play cards before then.', autoQueued: 'Next automatic action in about 1.5 seconds.', expired: 'Time up · waiting for the server',
    TURN: 'Normal turn · 30 seconds', NOPE_WINDOW: 'Nope window · 7 seconds', FAVOR_CHOICE: 'Choose a gift · 20 seconds', DEFUSE_INSERT: 'Insert explosion · 20 seconds', HIP_CAT_CHOICE: 'Rock / paper / scissors · 20 seconds', HIP_BAT_DISCARD: 'Hip Bat: discard one · 20 seconds', BATTLE_HAMSTER_DISCARD: 'Hamster: discard down to one · 20 seconds', ARCHAEOLOGY_CHOICE: 'Choose from discard · 20 seconds', FINISHED: 'Match finished',
    timeoutTURN: 'At timeout: the server draws one card and still handles explosions, Defuse and owed turns.', timeoutNOPE_WINDOW: 'At timeout: the server applies or cancels the action according to Nope parity.', timeoutFAVOR_CHOICE: 'At timeout: the server gives one random card.', timeoutDEFUSE_INSERT: 'At timeout: the server picks a random legal slot; middle positions stay hidden.', timeoutHIP_CAT_CHOICE: 'At timeout: the server picks randomly for unanswered players.', timeoutHIP_BAT_DISCARD: 'At timeout: the server discards one random card.', timeoutBATTLE_HAMSTER_DISCARD: 'At timeout: the server discards excess cards at random, leaving one.', timeoutARCHAEOLOGY_CHOICE: 'At timeout: the server picks a random eligible discard.', yourChoice: 'This step needs your response.', waitingFor: 'Waiting for {name}.', passed: 'You passed. You can still Nope if you change your mind.', chooseOne: 'Select exactly one card in your hand, then Confirm.', hamster: 'Discard {n} more cards, one selection at a time.', selected: 'Selected', cancel: 'Clear',
  },
};
export function coach(lang: Language, key: string, params: Record<string, string | number> = {}) {
  let value = (copy[lang] as Record<string, string>)[key] ?? key;
  for (const [name, replacement] of Object.entries(params)) value = value.replaceAll(`{${name}}`, String(replacement));
  return value;
}
export function QuickGuide({ lang }: { lang: Language }) {
  return <details className="quick-guide"><summary>{coach(lang, 'guide')}</summary><div>{['guideIntro', 'guideCombo', 'guideDebt', 'guideNope', 'guideHints', 'guideAuto'].map(key => <p key={key}>{coach(lang, key)}</p>)}</div></details>;
}
export function PlayModes({ lang, mode, onChange, extended }: { lang: Language; mode: ComposeMode; onChange: (mode: ComposeMode) => void; extended: boolean }) {
  return <fieldset className="mode-picker"><legend>{coach(lang, 'mode')}</legend>{(['SINGLE', 'PAIR', 'TRIPLE', ...(extended ? ['PLUS_PLUS'] : [])] as ComposeMode[]).map(value => <button key={value} type="button" aria-pressed={mode === value} onClick={() => onChange(value)}>{coach(lang, value)}</button>)}</fieldset>;
}
export function AutoControls({ lang, mode, onChange, queued }: { lang: Language; mode: AutoMode; onChange: (mode: AutoMode) => void; queued: boolean }) {
  return <div className="auto-controls"><label htmlFor="auto-mode">{coach(lang, 'auto')}</label><select id="auto-mode" value={mode} onChange={e => onChange(e.currentTarget.value as AutoMode)}>{(['OFF', 'DRAW', 'BASIC'] as const).map(value => <option key={value} value={value}>{coach(lang, value)}</option>)}</select>{mode !== 'OFF' && <p role="status">{coach(lang, mode === 'DRAW' ? 'drawRunning' : 'autoRunning')} {queued ? coach(lang, 'autoQueued') : ''}</p>}</div>;
}
export function PhaseCoach({ lang, game, selfId, seconds }: { lang: Language; game: PublicGame; selfId?: string; seconds: number }) {
  const pending = game.pending;
  const requiredId = ['FAVOR_CHOICE', 'HIP_BAT_DISCARD', 'BATTLE_HAMSTER_DISCARD'].includes(game.phase) ? pending?.targetPlayerId : game.phase === 'TURN' ? game.currentPlayerId : pending?.sourcePlayerId;
  const participant = requiredId === selfId || game.phase === 'HIP_CAT_CHOICE' && pending?.targetPlayerId === selfId;
  const name = game.players.find(p => p.id === requiredId)?.name ?? '…';
  const source = game.players.find(p => p.id === pending?.sourcePlayerId)?.name ?? '';
  const target = game.players.find(p => p.id === pending?.targetPlayerId)?.name;
  const nopeSummary = pending?.cardType ? `${source}: ${pending.playKind ? coach(lang, pending.playKind) : ''} · ${cardName(lang, pending.cardType)}${target ? ` → ${target}` : ''}${pending.requestedType ? ` · ${coach(lang, 'requested')}: ${cardName(lang, pending.requestedType)}` : ''}` : '';
  const total = game.phase === 'TURN' ? 30 : game.phase === 'NOPE_WINDOW' ? 7 : 20;
  return <section className={`phase-coach ${seconds <= 5 ? 'urgent' : ''}`} aria-label={coach(lang, game.phase)}><div><strong>{coach(lang, game.phase)}</strong><span>{game.phase === 'NOPE_WINDOW' ? nopeSummary : coach(lang, participant ? 'yourChoice' : 'waitingFor', { name })}</span></div><p>{seconds === 0 ? coach(lang, 'expired') : coach(lang, `timeout${game.phase}`)}</p><progress max={total} value={Math.min(total, seconds)} aria-label={lang === 'vi' ? 'Thời gian còn lại' : 'Time remaining'}/></section>;
}
