export const playfulEn: Record<string,string> = {
 'draft.house':'Application opening rule · 5 seconds', 'draft.title':'Pick your rescue cat', 'draft.hint':'Six physical Defuses, six expressions. First accepted pick keeps the card. After 5 seconds, the server assigns remaining cats to players who did not choose, then deals seven more cards each.', 'draft.choose':'Choose one available Defuse', 'draft.face':'Cat {n}', 'draft.seconds':'{n} seconds left', 'draft.confirmed':'Your cat is locked. Waiting for the deal.', 'draft.waiting':'Pick a cat, or let the server pick when time runs out.', 'draft.watching':'Watching the rescue cats find their humans.',
 'social.title':'Cat mischief', 'social.hint':'Just for laughs · no card or turn changes', 'social.target':'Aim at', 'social.EGG':'Egg', 'social.BOMB':'Toy bomb', 'social.ROCK':'Pebble', 'social.sending':'Incoming…', 'social.cooldown':'Catch your breath: {n}s', 'social.thrown':'{sourceName} threw a {propName} at {targetName}.', 'social.caption.EGG':'An omelette situation.', 'social.caption.BOMB':'Professionally startled.', 'social.caption.ROCK':'A very small inconvenience.',
 'error.REACTION_COOLDOWN':'Wait 1.5 seconds between throws.', 'error.DEFUSE_TAKEN':'Another cat picked that one first. Choose an available card.', 'error.DEFUSE_ALREADY_CHOSEN':'Your rescue cat is already locked.', 'error.DRAFT_FINISHED':'The five-second choice has ended.', 'error.INVALID_DEFUSE_SELECTION':'Choose a Defuse shown on this table.',
 'fx.eliminated':'Cat.exe stopped working.', 'fx.deadHint':'Your hand stays secret. Watch, chat or throw a toy.', 'fx.start':'Seven cards. One questionable plan.', 'fx.defuse':'Still alive. Mildly deflated.', 'fx.boom':'This cat seems professionally unwell.', 'fx.win':'Survival: unexpectedly successful.',
 'fx.ATTACK':'Your turn. Twice.', 'fx.FAVOR':'A small donation, please.', 'fx.NOPE':'Respectfully, absolutely not.', 'fx.SHUFFLE':'Memory has left the chat.', 'fx.SKIP':'Busy doing nothing.', 'fx.SEE_THE_FUTURE':'Three cards. Zero reassurance.', 'fx.AMATEUR_ARCHAEOLOGY':'Second-hand trouble.', 'fx.BATTLE_HAMSTER':'One card. Many feelings.', 'fx.CREEPY_PEEKY':'Privacy? Briefly absent.', 'fx.HIP_BAT':'Rent is due. In cards.', 'fx.HIP_CAT':'Hands up. Secretly.', 'fx.PLUS_PLUS':'A little extra trouble.', 'fx.ROBIN_HOOD':'Sharing is compulsory.', 'fx.THE_TWINS':'Double cat collection.', 'fx.RESURRECTION':'The cat has rebooted.',
};
export const playfulVi: Record<string,string> = {
 'draft.house':'Quy tắc mở ván của ứng dụng · 5 giây', 'draft.title':'Chọn mèo cứu mạng', 'draft.hint':'Sáu lá Cứu Nổ, sáu biểu cảm. Ai chọn trước giữ lá đó. Sau 5 giây, server phân lá còn lại cho người chưa chọn, rồi mới chia thêm 7 lá mỗi người.', 'draft.choose':'Chọn một lá Cứu Nổ còn trống', 'draft.face':'Mèo số {n}', 'draft.seconds':'Còn {n} giây', 'draft.confirmed':'Đã giữ mèo của bạn. Đợi chia bài nhé.', 'draft.waiting':'Chọn một mèo, hoặc để server chọn khi hết giờ.', 'draft.watching':'Đang xem mèo cứu mạng tìm chủ.',
 'social.title':'Mèo nghịch', 'social.hint':'Chỉ để vui · không đổi bài hay lượt', 'social.target':'Nhắm vào', 'social.EGG':'Trứng', 'social.BOMB':'Bom đồ chơi', 'social.ROCK':'Đá nhỏ', 'social.sending':'Đang bay…', 'social.cooldown':'Lấy hơi: {n}s', 'social.thrown':'{sourceName} ném {propName} vào {targetName}.', 'social.caption.EGG':'Có vẻ cần một cái chảo.', 'social.caption.BOMB':'Giật mình có chuyên môn.', 'social.caption.ROCK':'Phiền phức cỡ nhỏ.',
 'error.REACTION_COOLDOWN':'Đợi 1,5 giây giữa hai lần ném.', 'error.DEFUSE_TAKEN':'Mèo khác chọn trước rồi. Chọn lá còn trống nhé.', 'error.DEFUSE_ALREADY_CHOSEN':'Mèo cứu mạng của bạn đã được giữ.', 'error.DRAFT_FINISHED':'Đã hết 5 giây chọn mèo.', 'error.INVALID_DEFUSE_SELECTION':'Chọn một lá Cứu Nổ đang hiện trên bàn.',
 'fx.eliminated':'Mèo.exe đã ngừng hoạt động.', 'fx.deadHint':'Tay bài vẫn kín. Bạn có thể xem, chat hoặc ném đồ chơi.', 'fx.start':'Bảy lá bài. Một kế hoạch đáng ngờ.', 'fx.defuse':'Còn sống. Hơi xẹp.', 'fx.boom':'Con mèo này trông có vẻ không ổn.', 'fx.win':'Sống sót: thành công ngoài dự kiến.',
 'fx.ATTACK':'Tới bạn. Hai lần.', 'fx.FAVOR':'Xin tài trợ một lá.', 'fx.NOPE':'Xin phép từ chối toàn bộ.', 'fx.SHUFFLE':'Trí nhớ đã rời phòng.', 'fx.SKIP':'Bận không làm gì.', 'fx.SEE_THE_FUTURE':'Ba lá. Không yên tâm hơn.', 'fx.AMATEUR_ARCHAEOLOGY':'Rắc rối đã qua sử dụng.', 'fx.BATTLE_HAMSTER':'Một lá. Nhiều cảm xúc.', 'fx.CREEPY_PEEKY':'Quyền riêng tư tạm nghỉ.', 'fx.HIP_BAT':'Đến hạn đóng bài.', 'fx.HIP_CAT':'Giơ tay. Trong bí mật.', 'fx.PLUS_PLUS':'Thêm một chút rắc rối.', 'fx.ROBIN_HOOD':'Chia sẻ là bắt buộc.', 'fx.THE_TWINS':'Thu mèo theo đôi.', 'fx.RESURRECTION':'Mèo đã khởi động lại.',
};
